title: RB5_Robotics
email: avl@eng.ucsd.edu
institue: Contextual Robotics Institue
university: University of California, San Diego
description: >- # this means to ignore newlines until "baseurl:"
  Tutorials for RB5 on robotics.


theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  series:
    output: true


defaults:
  - scope:
      path: ""
      type: "series"
    values:
      layout: "serie"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"